### ISSUE TITLE
Rexnet-lite?

### ISSUE THREAD

**Issue by LeeKyungwook** [clovaai/rexnet#18]
Are there any plans to update the rexnet-lite model?

**Comment by dyhan0920** [comment]
@LeeKyungwook  The release of the entire ReXNet-lite models is being delayed due to internal issues.  Presumably, at least a single model will be released in a couple of days. Sorry for the late reply and late release of the models.

**Comment by LeeKyungwook** [comment]
@dyhan0920 Thanks for the answer! I hope that internal issues can be easily resolved.
