### ISSUE TITLE
pretrained models prolem

### ISSUE THREAD

**Issue by nankeqin** [clovaai/rexnet#19]
When I run

import torch
import rexnetv1

model = rexnetv1.ReXNetV1(width_mult=1.0).cuda()
model.load_state_dict(torch.load('./rexnetv1_1.0x.pth'))
model.eval()
print(model(torch.randn(1, 3, 224, 224).cuda()))

I met this problem：
TypeError:__init__() takes from 1 to 2 positional arguments but 3 were given

I did not change anything, how to solve it?

**Comment by OpenCDR** [comment]
I have the same problem. Have you solved it now？

**Comment by dyhan0920** [comment]
@nankeqin  @OpenCDR The code has been fixed. Sorry for the late update @nankeqin.

**Comment by nankeqin** [comment]
> @nankeqin @OpenCDR The code has been fixed. Sorry for the late update @nankeqin.

Problem was solved.Thank you.
