### ISSUE TITLE
404

### ISSUE THREAD

**Issue by LorenzoDag** [clovaai/rexnet#24]
In [README](https://github.com/clovaai/rexnet#-imagenet-classification-results) RexNet 1.3, 1.5 and 2.0 redirect to 404 error.

**Comment by dyhan0920** [comment]
ReXNet-lite is currently released only for the x1.0 model. If you need those models, please let me know.

**Comment by LorenzoDag** [comment]
Ok, thank you.
Just a question. I want to try to use this pretrained model to perform facial exprespression recognition. To obtain this, once i've loaded the weigths i need to add dense layer and train the new model. Is that right?

________________________________
Da: Greg Dongyoon Han ***@***.***>
Inviato: giovedì 29 luglio 2021 11:48
A: clovaai/rexnet ***@***.***>
Cc: D'AGOSTINO LORENZO ***@***.***>; Author ***@***.***>
Oggetto: Re: [clovaai/rexnet] 404 (#24)


ReXNet-lite is currently released only for the x1.0 model. If you need those models, please let me know.

**Comment by dyhan0920** [comment]
Thank you for using our backbones! 

Pretrained backbones are generally used replacing the last dense layer with a new one. Then, training is done only for the replaced dense layer with freezing some or entire convolution layers. However, sometimes, adding a single or couple of dense layers after the final dense layer of the backbone (as you asked) achieves better results on particular downstream tasks after training.  Please try both ways and pick a better one for your own task.

**Comment by LorenzoDag** [comment]
Ok. Thank you for helping me, and thank you for you work too.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by LorenzoDag** [comment]
excuse me sir,
is your model trained with 3 channels images?
________________________________
Da: Greg Dongyoon Han ***@***.***>
Inviato: giovedì 29 luglio 2021 18:55
A: clovaai/rexnet ***@***.***>
Cc: D'AGOSTINO LORENZO ***@***.***>; Author ***@***.***>
Oggetto: Re: [clovaai/rexnet] 404 (#24)


Thank you for using our backbones!

Pretrained backbones are generally used replacing the last dense layer with a new one. Then, training is done only for the replaced dense layer with freezing some or entire convolution layers. However, sometimes, adding a single or couple of dense layers after the final dense layer of the backbone (as you asked) achieves better results on particular downstream tasks after training. Please try both ways and pick a better one for your own task.

**Comment by dyhan0920** [comment]
@LorenzoDag Yes, please refer to the code.
