### ISSUE TITLE
pretrain rexnet lite

### ISSUE THREAD

**Issue by nightfuryyy** [clovaai/rexnet#27]
Thank you so much for awesome models. 
Could you please provide me rexnet_lite_1.3.pth,... ?
Thank you in advance.

**Comment by dyhan0920** [comment]
Thanks for your interest in our work!
I have released all the model files of ReXNet-lite's, please find the model files in README.md (https://github.com/clovaai/rexnet#-imagenet-classification-results)

**Comment by nightfuryyy** [comment]
Awesome !!! Thank you so much.
