### ISSUE TITLE
ONNX export failed: Couldn't export Python operator SiLUJitImplementation

### ISSUE THREAD

**Issue by xiangyun-hz** [clovaai/rexnet#32]
Thanks for sharing your wonderful work.

When I convert to onnx, I encounter a problem: ONNX export failed: Couldn't export Python operator SiLUJitImplementation.
The convert code is as follow:

def pth2onnx(model_name, model, input_shape):
    input_name = ["input"]
    output_name = ["output"]
    input = Variable(torch.randn(input_shape)).cpu()
    m_model = model.cpu()
    test_path = r'./'
    torch.onnx.export(m_model, input, model_name, input_names=input_name, output_names=output_name, verbose=False, opset_version=11)

Use the lastest code

**Comment by dyhan0920** [comment]
Thank you for your interest in our work!

The activation implementation is not compatible with the ONNX export of the model. Please set [this](https://github.com/clovaai/rexnet/blob/61debcc43d4ddce336427b5ef5250050a87dc230/rexnetv1.py#L13) to False for using the basic implementation. 

The memory increase will not be a matter in the running with the ONNX model.

**Comment by xiangyun-hz** [comment]
thank you for your reply, I know set USE_MEMORY_EFFICIENT_SiLU=False is well, but I want to know why? Does it affect performance or results？
